name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: List Current location
      run: pwd
    - name: Change to subdirectory
      run: ls
    - uses: actions/checkout@v2
    - name: make
      run: make
# Enable if tests are written
#    - name: make check
#      run: make check
