name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths:
      - 'mcp3008lsl/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'mcp3008lsl/*'
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Change to subdirectory
      run: cd mcp3008lsl/
    - uses: actions/checkout@v2
    - name: make
      run: make
# Enable if tests are written
#    - name: make check
#      run: make check
